require('model.serial.line_reader')

describe('LineReader', function()
  it('holds a partial line', function()
    local r = LineReader.new()
    assert.same({}, r:feed('ACK 4'))
    assert.same({ 'ACK 41' }, r:feed('1\n'))
  end)

  it('strips the terminator', function()
    local r = LineReader.new()
    assert.same({ 'ACK 41' }, r:feed('ACK 41\n'))
  end)

  it('strips CRLF', function()
    local r = LineReader.new()
    assert.same({ 'OK' }, r:feed('OK\r\n'))
  end)

  it('joins chunks', function()
    local r = LineReader.new()
    assert.same({}, r:feed('ACK '))
    assert.same({ 'ACK 41' }, r:feed('41\n'))
  end)

  it('splits one chunk into several lines', function()
    local r = LineReader.new()
    assert.same({ 'A', 'B', 'C' }, r:feed('A\nB\r\nC\n'))
  end)

  it('drops an overlong line', function()
    local r = LineReader.new(4)
    local lines, err = r:feed('TOOLONG\nOK\n')
    assert.same({ 'OK' }, lines)
    assert.same('overlong line dropped', err)
  end)

  it('drops overflow up to the next terminator', function()
    local r = LineReader.new(4)
    assert.same({}, r:feed('GARBAGEGARB'))
    local lines, err = r:feed('AGE\nOK\n')
    assert.same({ 'OK' }, lines)
    assert.same('overlong line dropped', err)
  end)

  it('forgets partial input on reset', function()
    local r = LineReader.new()
    r:feed('PART')
    r:reset()
    assert.same({ 'OK' }, r:feed('OK\n'))
  end)
end)
